name: flutter_pos
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Flutter 기본 아이콘을 사용하기 위한 패키지
  cupertino_icons: ^1.0.8

  # 상태 관리를 위한 패키지 (Provider 사용)
  provider: ^6.0.5

  # HTTP 요청을 처리하기 위한 패키지
  http: ^1.1.0
  
  
  # iOS/Android 스크롤 동작 개선
  sliding_up_panel: ^2.0.0


  # Socket 통신을 지원하기 위한 WebSocket 패키지
  web_socket_channel: ^2.3.0

  # Flutter UI 라이브러리 (특히 테이블 관리 UI 커스터마이징)
  flutter_staggered_grid_view: ^0.6.0

  # 네이티브 Toast 알림을 지원하기 위한 패키지
  fluttertoast: ^8.2.1

  # JSON 데이터 파싱을 쉽게 처리하기 위한 패키지
  json_serializable: ^6.5.4

  # Flutter Forms 및 유효성 검사 라이브러리
  flutter_form_builder: ^7.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 권장 코딩 스타일을 확인하기 위한 Linter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # 애셋 폴더를 사용하기 위해 추가
  #assets:
    #- assets/images/
    #- assets/icons/

  # 폰트가 필요할 경우 여기에 추가
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf



#dependencies:
  #flutter:
    #sdk: flutter
  #http: ^1.2.0          # 서버와 통신하기 위한 HTTP 패키지
  #provider: ^6.0.0      # 상태 관리를 위해 provider 사용
  #fluttertoast: ^8.0.9  # 알림 메시지를 표시하기 위한 패키지